### PR TITLE
feat: parsing for NakamotoCoinbase tx type

### PR DESCRIPTION
**Pull request by zone117x**
Implementing parsing for the new `NakamotoCoinbase` tx type. This tx type is mentioned in passing in [SIP-021](https://github.com/stacksgov/sips/blob/feat/sip-021-nakamoto/sips/sip-021/sip-021-nakamoto.md#new-block-validation-rules), the actual wire format is sourced from code here:
https://github.com/stacks-network/stacks-core/blob/05274b6366a1e29ab363fe294745ff813d70985f/stackslib/src/chainstate/stacks/transaction.rs#L275-L292

Test vector generated from a mockamoto node.

### CODE REVIEW

**Comment by janniks** [comment]
I'm not finding the length prefixed encoding for the VRF proof in the node code, where did you get this from? 🤔

**Comment by janniks** [comment]
Ok [found it](https://github.com/stacks-network/stacks-core/blob/6bdc9d5f8f872afd91a56089d7cceb7dcb7ddf9b/stacks-common/src/codec/mod.rs#L176-L192), I think the node meant to use different code, will open a PR

**Comment by janniks** [comment]
Looks good 👍 but I'll wait with approving until I know more on https://github.com/stacks-network/stacks-core/issues/4115 If you need it sooner, lmk

**Comment by zone117x** [comment]
@janniks I had the same thought. We'll wait to see if it's intended.

**Review by janniks — APPROVED** [review]
👏 looking good

**Pull request merged**
